jobs:
  Job1:
    name: Job 1a
    steps:
      - type: script
        script-content: echo %job1par1%
    parameters:
      job1par1: job1par1val
      job1par2: job1par2val
    output-parameters:
      job1par1: '%job1par1%'
    allow-reuse: false
  Job2:
    name: Job 2
    dependencies:
      - Job1
    steps:
      - type: script
        script-content: |-
          echo %job.Job1.job1par1%
          echo %job.Job1.job1par2%
    allow-reuse: false
  Job3:
    name: Job 3
    allow-reuse: false
    steps:
      - type: script
        script-content: echo %job.Job1.job1par1%
